### PR TITLE
Ft add group member #164867670

### PR DESCRIPTION
**Pull request by HabibSentongo**
This PR merges add group member branch to challenge3 branch.

@bekeplar @kyakusahmed @jenny @neelxie @nanfuka @Wabuluka

### CODE REVIEW

**Comment by neelxie** [comment]
Bro i see the config file empty is it supposed to be that way?

**Comment by HabibSentongo** [comment]
@neelxie I canceled using that one because I am using .environment variables files, I am going to remove it. Thanks for the reminder.

**Comment by bekeplar** [comment]
Hello...avoid having commented code in your application code

**Comment by bekeplar** [comment]
Also I see datastructure key wordslike append..Kindly look into it

**Pull request merged**
